language: scala

jobs:
  include:
    - name: "Tests"
      cache:
        directories:
          - $HOME/.cache/coursier
          - $HOME/.ivy2/cache
          - $HOME/.sbt
          - $HOME/.cache/pip
          - $HOME/.cache/pyenv
      before_cache:
        - rm -fv $HOME/.ivy2/.sbt.ivy.lock
        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        - find $HOME/.sbt        -name "*.lock"               -print -delete
      install:
        - pyenv install -s 3.7.1
        - pyenv global 3.7.1
        - pip install -r requirements.txt
        - export LD_LIBRARY_PATH=$(python3-config --prefix)/lib

      script:
        - sbt test

    - name: "Website"
      install:
        - cd website
        - npm install
      script:
        - npm run build
        - touch build/.nojekyll
      deploy:
        provider: pages
        local_dir: website/build/tf-dotty
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master

    - stage: release
      name: "Release library"
      before_install:
        - git fetch --tags
      script: sbt ci-release
