language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

install:
  - pyenv install -s 3.6.3
  - pyenv global 3.6.3
  - pip install jep

script:
  - export JEP_PATH="/opt/python/3.6.3/lib/python3.6/site-packages/jep"
  - export LD_LIBRARY_PATH=$(python3-config --prefix)/lib
  - sbt test
